#JMB 2022 -- Taken from https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# changelog:
#   exclude:
#     labels:
#       - ignore-for-release
#     authors:
#       - octocat
#   categories:
#     - title: Nouvelles User Stories & Features 🎉
#       labels:
#         - us
#         - feature
#         - enhancement
#     - title: Fix et améliorations 🛠
#       labels:
#         - bug
#         - improve
#     - title: Autres changements
#       labels:
#         - "*"

# **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'Code JAVA'
    label: 'type: JAVA'
  - title: 'Code PYTHON'
    label: 'type: PYTHON'
  - title: 'Documentation'
    label: 'type: DOCS'
  - title: 'Code BD'
    label: 'type: BD'
  - title: 'Code WEB'
    label: 'type: WEB'
  - title: 'Other changes'
    collapse-after: 6

version-resolver:
  major:
    labels:
      - 'type: JAVA'
      - 'type: PYTHON'
      - 'type: DOCS' 
      - 'type: BD' 
      - 'type: WEB'
exclude-labels:
  - 'skip-changelog'
