= Documentation Installation Python
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

toc::[]

== Installation

===  Prérequis

Pour pouvoir lancer l'application, il faut la lancer sur une machine Ubuntu dans un environnement UNIX car une machine window ne reconnaitra pas les _signal.alarm()_ . 

===  Version de Python

Il faut utiliser à minima la ``version 3.2`` de Python (Pour que les _interpolation_ de _configparser_ fonctionne).

Pour cela, faire la commande ``python --version``. +
Si s'affiche un message d'erreur, c'est que python n'est pas installé ou si s'affiche une version de python antérieur à la version 3.2, faire la commande ``sudo apt-get install python3._X_`` avec X pour le numéro de version (soit 2 ou plus).

===  Installation

Installer la bibliothèque paho mqtt :
``pip install paho-mqtt``

Les autres bibliothèque utilsé sont des import en python.


== Lancement

Une fois installé correctement, récuperer la fichier de l'application https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/blob/master/Applications/Python/app.py[ici], le fichier de configuration https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/blob/master/Applications/Python/config.ini[ici], le fichier d'alarmes https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/blob/master/Applications/Python/alarmes.txt[ici] et le fichier des données https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/blob/master/Applications/Python/data.json[ici] +

Mettre tout ses fichier dans un dossier.
Et voici la commande qu'il faut exécuter pour lancer l'application : +
``python3 app.py``
