= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/jordanQuin[Jordan Quinveros]
- https://github.com/Guilhamasse[Quentin Guilhamasse]
- https://github.com/AdrielMarchant[Adriel Marchant]
- https://github.com/Antoine3312[Antoine Mazeau]
- https://github.com/mathislht[Mathis Lahitte]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:andre.peninou@univ-tlse2.fr[Andre Peninou]

== Réalisations

=== Gestion de projet

|=============
|Nom fichier|Liens
|Liste des US en cours |https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/milestone/3
|Backlog du sprint |
|Version courante du projet|https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/releases/tag/V0.03[V3.0]
|=============

=== Documentation

|=============
|Nom fichier|Liens
|DCE |https://docs.google.com/document/d/1z3mgQRoSlLEJZFmZFSlrtSRUDlVCf9nbzokAtmIpE4k/edit
|CDCF |https://docs.google.com/document/d/1IU6dr1NM6qHMl-TdcAE7Pqclu0MrQrqmcuWVcIt_VLo/edit
|CDCT |https://docs.google.com/document/d/1ZTP3Ixq39regdlD_80VxalwgXkqIwEX00pqX56ker8Y/edit
|Doc python |https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/blob/master/appPython/documentation.adoc
|=============

=== Web

|=============
|Nom fichier|Liens
|Code du site web|https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/tree/master/Applications/Web
|Lien du site (interne IUT)|http://192.168.224.138/~SAESYS02/SAE/Index/
|Lien du site (externe IUT)|http://193.54.227.164/~SAESYS02/SAE/Index/
|=============

=== Application

|=============
|Nom fichier|Liens
|Application Python|https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/tree/master/Applications/Web
|=============


TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)



== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/releases/tag/V3.0[v3.0]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

=== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1232553383&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1232553383&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1232553383&format=image"></iframe>
++++
endif::[]

=retour sprint 3 : 
Il manque la prorité sur les US des backlogs. Le backlog E commerce reste incomplet. Les tâches ne sont pas assez décomposées, je dois avoir les tâches techniques … peu de tâches dans ce sprint et … rien en done ! Backlog IOT très limité ! Doc : uniquement le schéma web, pas de doc tech, pas de doc user. Release à V0 ... dans le readme. Rien sur les tests
